#!/usr/bin/env bash
# script that will display information about subdomains.

function single_domain_details {
	dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
	awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

function all_domain_details {
	domain_names=("www" "lb-01" "web-01" "web-02")

	for i in "${domain_names[@]}";
	do
		dig "${i}"."$1" | grep -A1 'ANSWER SECTION:' | \
		awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$i"
	done
}


if [ $# -lt 1 ]
then
	echo "Domain name required"
elif [ $# -eq 1 ]
then
	all_domain_details "$1";
else
	single_domain_details "$1" "$2";
fi
