#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

i=0

while [ $i -le 12 ]; do
	echo "Hour: $i"

	j=1
	while [ $j -lt 60 ]; do
		echo "$j"
		((j++))
	done
	((i++))
done
