#!/usr/bin/env bash
# Configures ufw so that it blocks all incoming traffic, except the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)

apt-get -y update
apt -y install ufw

#modifying config file to accept IPv6 connections
sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw

# setting up default policies
ufw default deny incoming
ufw default allow outgoing

# allowing ssh, http and https connections
ufw allow ssh
ufw allow http
ufw allow https

echo 'y' | sudo ufw enable
